resourcePack:
  url: "https://download.mc-packs.net/pack/9586c10668316da2c4282fa49aa04a43b83aeb0c.zip"
  hash: "" # Peut être laisser vide, sera générer par le plugin lors du premier chargement du plugin
  mandatory: true # Détermine si le resource pack est obligatoire
