resourcePack:
  url: "https://download.mc-packs.net/pack/65e23c62cfa9738c35fd736b237626f8226a3c2a.zip" # URL de base (utilisée avant fusion)
  mandatory: true # Détermine si le resource pack est obligatoire
